# Generated by Django 5.0.6 on 2024-08-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='is_shelter_owner',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
