FROM python:3.12

WORKDIR /pet_seeker

COPY pet_seeker/requirements.txt /pet_seeker/

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY /pet_seeker /pet_seeker/

EXPOSE 8000

RUN python manage.py makemigrations
RUN python manage.py migrate

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]