version: '3'

services:
  rest-framework:
    build: .
    entrypoint: /code/entrypoint.sh
    restart: always
    container_name: rest-framework
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=123321
      - DJANGO_SUPERUSER_EMAIL=admin@gmail.com
    depends_on:
      - pgdb
  pgdb:
    image: postgres:12
    restart: always
    container_name: pgdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  nginx:
    image: nginx:1.24.0
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    ports:
      - "80:80"