# Generated by Django 5.0.6 on 2024-07-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_announcement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelterannouncement',
            name='price',
        ),
    ]
