# Generated by Django 5.0.6 on 2024-08-09 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelterannouncement',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shelterannouncement',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='shelterannouncement',
            name='contacts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shelterannouncement',
            name='dimmensions',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='shelterannouncement',
            name='lattitude_longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shelterannouncement',
            name='status',
            field=models.CharField(choices=[('Нашел', 'Find'), ('Потерял', 'Lost'), ('Ищет дом', 'Looking Home')], default='Ищет дом', max_length=50),
        ),
        migrations.AlterField(
            model_name='shelterannouncement',
            name='weigth',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
    ]
