# Generated by Django 5.0.6 on 2024-07-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_announcement', '0002_remove_shelterannouncement_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelterannouncement',
            name='location',
        ),
        migrations.AddField(
            model_name='shelterannouncement',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelterannouncement',
            name='lattitude_longitude',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
