# Generated by Django 5.0.6 on 2024-07-24 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_announcement', '0004_shelterannouncement_allergenicity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelterannouncement',
            name='is_health_issues',
        ),
    ]
