# Generated by Django 5.0.6 on 2024-07-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='location',
            field=models.CharField(default='ginger', max_length=200),
            preserve_default=False,
        ),
    ]
