# Generated by Django 5.0.6 on 2024-07-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userinfo_contacts_alter_userinfo_is_shelter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='shelter_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
