# Generated by Django 5.0.6 on 2024-07-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userinfo_shelter_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='is_shelter',
            new_name='is_shelter_owner',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='shelter_number',
        ),
    ]
