# Generated by Django 5.0.6 on 2024-07-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_is_shelter_userinfo_is_shelter_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
