# Generated by Django 5.0.6 on 2024-07-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userinfo_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='location',
        ),
    ]
