# Generated by Django 5.0.6 on 2024-07-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
