# Generated by Django 5.0.6 on 2024-08-02 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('lattitude_longitude', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacts', models.CharField(max_length=100)),
                ('pet_type', models.CharField(blank=True, choices=[('Собака', 'Dog'), ('Кошка', 'Cat')], max_length=50, null=True)),
                ('state', models.CharField(choices=[('Активный', 'Active'), ('В процессе усыновления', 'In Process'), ('Неактивный', 'Inactive')], default='Активный', max_length=50)),
                ('status', models.CharField(choices=[('Нашел', 'Find'), ('Потерял', 'Lost'), ('Ищет дом', 'Looking Home')], max_length=50)),
                ('breed', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.BooleanField()),
                ('wool_type', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(max_length=50)),
                ('sterilization', models.BooleanField(null=True)),
                ('allergenicity', models.BooleanField(null=True)),
                ('health_issues', models.CharField(blank=True, max_length=200, null=True)),
                ('vaccinations', models.BooleanField(null=True)),
                ('weigth', models.FloatField()),
                ('dimmensions', models.PositiveIntegerField()),
                ('temperament', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at'],
                'abstract': False,
            },
        ),
    ]
