# Generated by Django 5.0.6 on 2024-07-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='breed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='dimmensions',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='health_issues',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_health_issues',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='pet_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('Активный', 'Active'), ('В процессе усыновления', 'In Process'), ('Неактивный', 'Inactive')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='sterilization',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='temperament',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='vaccinations',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='weigth',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
