# Generated by Django 5.0.6 on 2024-07-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_announcement_age_announcement_breed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='vaccinations',
            field=models.BooleanField(null=True),
        ),
    ]
