# Generated by Django 5.0.6 on 2024-07-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_alter_announcement_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-published_at']},
        ),
    ]
