# Generated by Django 5.0.6 on 2024-07-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_alter_announcement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='pet_type',
            field=models.CharField(blank=True, choices=[('Собака', 'Dog'), ('Кошка', 'Cat')], max_length=50, null=True),
        ),
    ]
