# Generated by Django 5.0.6 on 2024-07-14 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_alter_announcement_pet_type'),
        ('shelter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcement',
            new_name='PrivateAnnouncement',
        ),
        migrations.CreateModel(
            name='ShelterAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet_type', models.CharField(blank=True, choices=[('Собака', 'Dog'), ('Кошка', 'Cat')], max_length=50, null=True)),
                ('breed', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Активный', 'Active'), ('В процессе усыновления', 'In Process'), ('Неактивный', 'Inactive')], max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('sterilization', models.BooleanField(null=True)),
                ('is_health_issues', models.BooleanField()),
                ('health_issues', models.CharField(blank=True, max_length=200, null=True)),
                ('vaccinations', models.BooleanField(null=True)),
                ('weigth', models.FloatField()),
                ('dimmensions', models.PositiveIntegerField()),
                ('temperament', models.CharField(blank=True, max_length=100, null=True)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='shelter.shelter')),
            ],
            options={
                'ordering': ['-published_at'],
                'abstract': False,
            },
        ),
    ]
