# Generated by Django 5.0.6 on 2024-07-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0008_remove_privateannouncement_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateannouncement',
            name='location',
        ),
        migrations.AddField(
            model_name='privateannouncement',
            name='address',
            field=models.CharField(default='деревня Запиздяевка', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privateannouncement',
            name='lattitude_longitude',
            field=models.CharField(default='123, 312', max_length=100),
            preserve_default=False,
        ),
    ]
