# Generated by Django 5.0.6 on 2024-07-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0010_alter_privateannouncement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateannouncement',
            name='allergenicity',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='privateannouncement',
            name='contacts',
            field=models.CharField(default='ginger', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privateannouncement',
            name='gender',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privateannouncement',
            name='state',
            field=models.CharField(choices=[('Активный', 'Active'), ('В процессе усыновления', 'In Process'), ('Неактивный', 'Inactive')], default='Активный', max_length=50),
        ),
        migrations.AddField(
            model_name='privateannouncement',
            name='wool_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='privateannouncement',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='privateannouncement',
            name='status',
            field=models.CharField(choices=[('Нашел', 'Find'), ('Потерял', 'Lost'), ('Ищет дом', 'Looking Home')], max_length=50),
        ),
    ]
