# Generated by Django 5.0.6 on 2024-07-24 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0011_privateannouncement_allergenicity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateannouncement',
            name='is_health_issues',
        ),
    ]
