# Generated by Django 5.0.6 on 2024-07-27 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelter', '0006_shelter_user'),
        ('user', '0016_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_images')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ShelterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shelter_images')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.shelter')),
            ],
        ),
    ]
