# Generated by Django 5.0.6 on 2024-07-27 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0012_remove_privateannouncement_is_health_issues'),
        ('image_loader', '0001_initial'),
        ('shelter', '0006_shelter_user'),
        ('user', '0016_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='user_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to='user.userinfo'),
        ),
        migrations.AlterField(
            model_name='shelterimage',
            name='image',
            field=models.ImageField(upload_to='shelter_images/'),
        ),
        migrations.AlterField(
            model_name='shelterimage',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shelter.shelter'),
        ),
        migrations.CreateModel(
            name='PrivateAnnouncementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announcement_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='announcement.privateannouncement')),
            ],
        ),
    ]
