# Generated by Django 5.0.6 on 2024-07-28 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_loader', '0002_alter_profileimage_image_and_more'),
        ('shelter_announcement', '0005_remove_shelterannouncement_is_health_issues'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterAnnouncementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announcement_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shelter_announcement.shelterannouncement')),
            ],
        ),
    ]
