# Generated by Django 5.0.6 on 2024-08-06 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='inn_orn',
            field=models.CharField(default='пизда', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
