# Generated by Django 5.0.6 on 2024-07-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='lattitude_longitude',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
