# Generated by Django 5.0.6 on 2024-07-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_shelter_lattitude_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='contacts',
            field=models.CharField(default='88005553535', max_length=100),
            preserve_default=False,
        ),
    ]
