# Generated by Django 5.0.6 on 2024-08-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_shelter_inn_orn_shelter_registered_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelter',
            old_name='inn_orn',
            new_name='inn_ogrn',
        ),
    ]
