# Generated by Django 5.0.6 on 2024-07-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_shelter_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='address',
            field=models.CharField(default='ginger', max_length=100),
            preserve_default=False,
        ),
    ]
