# Generated by Django 5.0.6 on 2024-07-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0004_shelter_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='user',
        ),
    ]
